SCORE_LONG_DOMAIN      = 25
SCORE_LONG_LABEL       = 25
SCORE_HIGH_ENTROPY     = 25
SCORE_HIGH_RATE        = 15
SCORE_MANY_SUBDOMAINS  = 15
SCORE_ABUSE_QTYPE      = 10

DOMAIN_LENGTH_THRESHOLD    = 80
LABEL_LENGTH_THRESHOLD     = 50
ENTROPY_THRESHOLD          = 4.2
RATE_PER_MIN_THRESHOLD     = 30
UNIQUE_SUBDOMAIN_THRESHOLD = 25

ABUSED_QTYPES = {"TXT", "NULL", "CNAME"}

RATE_WINDOW_SECONDS = 60
